rango/urls.py
from django.urls import path
from rango import views
app_name = 'rango'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),

   path('category/<slug:category_name_slug>/',
       views.show_category, name='show_category'),

]

tango_with_django_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from rango import views
from django.contrib import admin
from django.urls import path
from django.urls import include
urlpatterns = [
    path('', views.index, name='index'),
    path('rango/', include('rango.urls')),
    # The above maps any URLs starting with rango/ to be handled by rango.
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
slug = models.SlugField(unique=True)

class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    likes = models.IntegerField(default=0)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
  
    def __str__(self):
        return self.title

rango/forms.py
from django import forms
from rango.models import Page, Category

class CategoryForm(forms.ModelForm):
  name = forms.CharField(max_length=128,help_text="Please enter the category name.")
  views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
  likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
  slug = forms.CharField(widget=forms.HiddenInput(), required=False)

  # An inline class to provide additional information on the form.
  class Meta:
  # Provide an association between the ModelForm and a model
    model = Category
    fields = 'name',
class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
    help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
    help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
     # Provide an association between the ModelForm and a model
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values; we may not want to include them.
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,
        exclude = ('category',)
       # or specify the fields to include (

class PageForm(forms.ModelForm):
    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')
        # If url is not empty and doesn't start with 'http://',
        # then prepend 'http://'.
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url
        return cleaned_data

rango/views.py
from rango.forms import CategoryForm
from django.shortcuts import redirect
from django.shortcuts import render
from rango.models import Category
from rango.models import Page
from django.http import HttpResponse
from django.shortcuts import redirect
from django.urls import reverse
def index(request):
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]

    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list

    # Render the response and send it back!
    return render(request, 'rango/index.html', context=context_dict)
def show_category(request, category_name_slug):
    # Create a context dictionary which we can pass
    # to the template rendering engine.
    context_dict = {}
    try:
            # Can we find a category name slug with the given name?
            # If we can't, the .get() method raises a DoesNotExist exception. 
            # The .get() method returns one model instance or raises an exception.
        category = Category.objects.get(slug=category_name_slug)

             # Retrieve all of the associated pages.
             # The filter() will return a list of page objects or an empty list.
        pages = Page.objects.filter(category=category)

            # Adds our results list to the template context under name pages.
        context_dict['pages'] = pages
             # We also add the category object from
             # the database to the context dictionary.
             # We'll use this in the template to verify that the category exists.
        context_dict['category'] = category
    except Category.DoesNotExist:
           # We get here if we didn't find the specified category.
            # Don't do anything -
            # the template will display the "no category" message for us.
        context_dict['category'] = None
        context_dict['pages'] = None
            # Go render the response and return it to the client.
    return render(request, 'rango/category.html', context=context_dict) 
  
def add_category(request):
  form = CategoryForm()
  # A HTTP POST?
  if request.method == 'POST':
    form = CategoryForm(request.POST)
    # Have we been provided with a valid form?
    if form.is_valid():
      # Save the new category to the database.
      cat=form.save(commit=True)
      # Now that the category is saved, we could confirm this.
      # For now, just redirect the user back to the index view.
      return redirect('/rango/')
    else:
 
      # just print them to the terminal.
      print(form.errors)
  # Will handle the bad form, new form, or no form supplied cases.
  # Render the form with error messages (if any).
  return render(request, 'rango/add_category.html', {'form': form})

def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    # You cannot add a page to a Category that does not exist...
    if category is None:
        return redirect('/rango/')
    form = PageForm()

    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return redirect(reverse('rango:show_category',kwargs={'category_name_slug':category_name_slug}))
        else:
           print(form.errors)
        context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)


def about(request):

    return render(request, 'rango/about.html' , {})

templates/rango/about.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
  {% if about %}
    {{About Rango. }}
  {% else %}
    <strong>{{This tutorial has been put together by Teame Habtu}}</strong><br />
  {% endif %}
  {% else %}
    <img src="{% static 'images/rango.jpg' %}"alt="Picture of Rango" />
    <img src="{ { MEDIA_URL }}'cat.jpg' %}" alt="Picture of a Cat" />
  {% endif %}
  
{% endblock %}

templates/rango/add_category.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
 {% if category %}
   {{Add a Category.  }}
 {% else %}
     Unknown Category
  {% endif %}
{% endblock %}
{% block body_block %}
   {% if category %}
      {{Add a Category.  }}
   {% else %}
    <form id="category_form" method="post" action="/rango/add_category/">
      {% csrf_token %}
    {% block body_block %}
       {% for hidden in form.hidden_fields %}
           {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
      {{ field.errors }}
      {{ field.help_text }}
      {{ field }}
  {% endfor %}
  {% endif %}
  {% else %}
  <input type="submit" name="submit" value="Create Category" />
  {% endif %}
{% endblock %}
    

templates/rango/add_page.html
!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
 {% if add_page %}
    {{ Add a Page }}
  {% else %}
     Unknown Category
  {% endif %}
{% endblock %}

{% block body_block %}
  {% if add_pages %}
  <h1>{{Add a Page.}}</h1>
  {% else %}
  <form id="add_page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">
    {% csrf_token %}
      {% csrf_token %}
      {% for hidden in form.hidden_fields %}
           {{ hidden }}
    {% endfor %}
    {% for field in form.visible_fields %}
      {{ field.errors }}
      {{ field.help_text }}
      {{ field }}
  {% endfor %}
  {% endif %}
  {% else %}
   <input type="submit" name="submit" value="Add Page" />
  {% endif %}
  </form>
{% endblock %}
    

templates/rango/base.html
<!DOCTYPE html>
 {% load staticfiles %}

<html>
  <head>
     <title>
       Rango -
       {% block title_block %}
         How to Tango with Django!
       {% endblock %}
     </title>
   </head>
   <body>
    <div>
    {% block body_block %}
    {% endblock %}
    </div>
    <hr />
   <div>
     <ul>
       <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></l\ i>
      <li><a href="{% url 'rango:about' %}">About</a></li>
      <li><a href="{% url 'rango:index' %}">Index</a></li>
    </ul>
  </div>
 </body>
</html>

templates/rango/category.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  {% if category %}
    {{ name –}}
  {% else %}
     Unknown Category
  {% endif %}
{% endblock %}

{% block body_block %}
  {% if category %}
  <h1>{{ category.name }}</h1>
  {% if pages %}
  <ul>
    {% for page in pages %}
    <li><a href="{{ page.url }}">{{ page.title }}</a></li>
    {% endfor %}
  </ul>
  {% else %}
  <strong>No pages currently in category.</strong>
  {% endif %}

  <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br />
  {% else %}
  The specified category does not exist.
  {% endif %}
{% endblock %}

templates/rango/index.html
!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
  {% if index %}
   {{  Homepage. }}
  {% else %}
     Unknown Category
  {% endif %}
{% endblock %}
<h2>Most Liked Categories.<h2>
{% block body_block %}
  {% if categories %}
  {% for category in categories %}
    <a href="{% url 'rango:show_category' category.slug %}">
        {{ category.name }}
    </a>
  {% endfor %}
  {% endif %}
  {% if pages %}
  <h2>Most viewed pages<h2>
    <ul>
      {% for page in pages %}
          <li><a href="{{page.url }}">{{ page.title }}</a></li>
      {% endfor %}
      </ul>
     {% endif %}
      <img src="{% static "images/rango.jpg" %}"
      alt="Picture of Rango" />
  {% endfor %}
  {% endif %}
{% endblock %}
 
 #  <a href="{% url 'add_page' category.slug %}">Add Page</a> <br />
  